name: Entrega Continua

on:
  workflow_call: 

jobs:
  EC2:
    runs-on: 'ubuntu-latest'
    steps:
     #DOWNLOAD DE ARTEFATOS
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: programa

    - name: Listar conteúdo do artefato baixado
      run: ls -la

    - name: Copy file via SSH password
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "main"
        target: "/home/${{ secrets.REMOTE_USER }}"


    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: | 
          echo "Verificando arquivos no EC2..."
          ls -la /home/${{ secrets.REMOTE_USER }}
          rm -f /home/${{ secrets.REMOTE_USER }}/main /home/${{ secrets.REMOTE_USER }}/main.exe
          export DB_HOST=${{ secrets.DB_HOST }} 
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }} 
          export DB_USER=${{ secrets.DB_USER }} 
          export DB_NAME=${{ secrets.DB_NAME }} 
          export DB_PORT=${{ secrets.DB_PORT }} 
          export PORT=8000
          chmod +x /home/${{ secrets.REMOTE_USER }}/main
          nohup /home/${{ secrets.REMOTE_USER }}/main > nohup.out 2> nohup.err < /dev/null &
        